### ISSUE TITLE
Add support to get a random joke by type

### ISSUE THREAD

**Issue by cool-mist** [seburbandev/chuckle-cli#1]
Thanks for doing this cli. It would be a good addition to allow getting jokes by type (especially I'm only interested in the programming ones :P).

Eg:

`chuckle programming` - to get a random joke from programming category
`chuckle` - to get a random joke

**Comment by seburbandev** [comment]
@cool-mist Thanks for submitting your suggestion. This feature is currently under development. I still need to think about how I would like the flags to work, what to name them etc. I'm hoping to get it released by end of August but it really depends on my availability.
